configurations: []
executionInputs: []
triggers:
  - name: '1'
    type: plugin
    description: '1'
    plugin: gitops
    configuration: null
    method: push-branch
    params:
      - name: branches
        value: null
      - name: branchesIgnore
        value: null
steps:
  - params:
      - name: COMMANDS
        code: false
        value: sleep 30
      - name: finishSignal
        code: false
        value: exit
      - name: shell
        code: false
        value: default
      - name: workingDir
        code: false
        value: null
    type: plugin
    id: CommandLine1
    displayName: Command Line
    timeout: null
    agent: null
    retries: null
    plugin: CommandLine@3.2.1
    pluginAccount: null
    method: execute
    nextStep: null
kaholoVersion: 6.2.0
name: pipeline03
description: ''
agent: null
timeout: null
maxConcurrency: 1
firstStep: CommandLine1
